name: graph
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - glew=2.2.0
  - glib=2.78.4
  - pip=24.0
  - python=3.9
  - pytorch
  - pytorch-cuda=12.4
  - torchvision
  - pip:
    - absl-py==2.1.0
    - dm-control==1.0.8
    - glfw==2.7.0
    - ffmpeg==1.4
    - imageio==2.34.1
    - imageio-ffmpeg==0.4.9
    - h5py==3.11.0
    - hydra-core==1.3.2
    - hydra-submitit-launcher==1.2.0
    - submitit==1.5.1
    - omegaconf==2.3.0
    - moviepy==1.0.3
    - mujoco==2.3.1
    - numpy==1.24.4
    - tensordict-nightly
    - torchrl-nightly
    - kornia==0.7.2
    - termcolor==2.4.0
    - tqdm==4.66.4
    - pandas==2.0.3
    - wandb==0.17.4
    - matplotlib==3.7.5
    - seaborn==0.13.2
    - gpustat==1.1.1
    ####################
    # Gym:
    # (unmaintained but required for maniskill2/meta-world/myosuite)
    - gym==0.21.0
    ####################
    # ManiSkill2:
    # (requires gym==0.21.0 which occasionally breaks)
    # - mani-skill2==0.4.1
    ####################
    # Meta-World:
    # (requires gym==0.21.0 which occasionally breaks)
    # - git+https://github.com/Farama-Foundation/Metaworld.git@04be337a12305e393c0caf0cbf5ec7755c7c8feb
    ####################
    # MyoSuite:
    # (requires gym==0.13 which conflicts with meta-world / mani-skill2)
    # - myosuite
    ####################
